version: "3.9"

services:

  frontend:

    image: mahi271/frontend-app:v1

    ports:
      - "8081:80"

    depends_on:
      - backend

  backend:

    image: mahi271/backend-api:v1

    ports:
      - "5001:5000"